name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23liJrAUTTkwHzG1nV"
GITHUB_OWNER = "zzoe110"
GITHUB_REPO = "WWWSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://4925e0ff.wwwsphere.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://4925e0ff.wwwsphere.pages.dev/"

